INSERT INTO genres (name, search_terms) VALUES
  ('Bollywood', ARRAY['bollywood hits', 'hindi songs 2026']),
  ('Pop', ARRAY['pop hits', 'top pop songs']),
  ('Hip-Hop / Rap', ARRAY['hip hop hits', 'rap songs']),
  ('Electronic / EDM', ARRAY['edm hits', 'electronic dance music']),
  ('Indie', ARRAY['indie hits', 'indie pop']),
  ('Punjabi', ARRAY['punjabi hits', 'punjabi songs']),
  ('Rock', ARRAY['rock hits', 'rock songs']),
  ('R&B / Soul', ARRAY['rnb hits', 'soul music']),
  ('Classical (Indian)', ARRAY['indian classical music', 'hindustani classical']),
  ('Devotional / Bhajan', ARRAY['bhajan songs', 'devotional hindi songs']),
  ('Sufi', ARRAY['sufi songs', 'sufi music']),
  ('Ghazal', ARRAY['ghazal songs', 'best ghazals']),
  ('Party / Dance', ARRAY['party songs', 'dance hits']),
  ('Romantic', ARRAY['romantic hindi songs', 'love songs']),
  ('Lo-fi / Chill', ARRAY['lofi songs', 'chill music']),
  ('K-Pop', ARRAY['kpop hits', 'korean pop songs']),
  ('Metal', ARRAY['metal songs', 'heavy metal hits']),
  ('Jazz', ARRAY['jazz songs', 'jazz classics']),
  ('South Indian (Tamil/Telugu)', ARRAY['tamil hits', 'telugu songs']),
  ('Folk', ARRAY['indian folk songs', 'folk music']);